### ISSUE TITLE
Error reading from database

### ISSUE THREAD

**Issue by Brada65** [catalyst/moodle-report_apocalypse#4] opened 2018-12-05 11:59 UTC
Moodle 3.3, 3.4 and 3.6
report_apocalypse_moodle36_2018051400

Error code: dmlreadexception
Stack trace:

    line 486 of /lib/dml/moodle_database.php: dml_read_exception thrown
    line 1245 of /lib/dml/mysqli_native_moodle_database.php: call to moodle_database->query_end()
    line 1571 of /lib/dml/moodle_database.php: call to mysqli_native_moodle_database->get_records_sql()
    line 1644 of /lib/dml/moodle_database.php: call to moodle_database->get_record_sql()
    line 1854 of /lib/dml/moodle_database.php: call to moodle_database->get_field_sql()
    line 143 of /report/apocalypse/index.php: call to moodle_database->count_records_sql()

**Comment by danmarsden** [comment] 2018-12-05 18:12
Thanks for the report - I think this is a duplicate of issue #1 which has just been fixed here in github. I'll push out this release into the plugins db soon.

**Closed as completed by danmarsden** 2018-12-05 18:12 UTC
